name: Flutter CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Flutter
        uses: subosito/flutter-action@v1

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: flutter pub get

      - name: Test
        run: flutter test

      - name : Create
        run: flutter create

      - name: Run
        run: flutter run

      - name: Build APK
        run: flutter build apk

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-results
          path: |
            ./build/app/outputs/apk/
            ./build/ios/
